name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd ~/WebpageTask || git clone https://github.com/Niamh13/WebpageTask.git ~/WebpageTask

            cd ~/WebpageTask

            git pull origin main

            npm install

            pm2 restart mathapp || pm2 start npm --name mathapp -- start
